server:
  address: ":8080"
  shutdown_timeout: 30s
  read_timeout: 15s
  write_timeout: 15s

auth:
  jwt_secret: "secretkey"
  jwt_access_expiry: 15m
  jwt_refresh_expiry: 168h  # 7 days
  token_refresh_leeway: 5m

database:
  type: "postgres"
  connection_retries: 5
  retry_delay: 1s
  postgres:
    host: "localhost"
    port: "5433"
    uri: "postgresql://admin:secret@127.0.0.1:5432/mydb?sslmode=disable"
    user: "admin"
    password: "secret"
    dbname: "mydb"
    sslmode: "disable"
    max_open_conns: 30
    max_idle_conns: 10
    max_lifetime: 30m
    log_level: "info"
    search_path: "app_schema"

logger:
  level: "debug"
  format: "text"
  output: "stdout"
  with_caller: true